spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store
    username: user
    password: pas123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10 # Configuraci√≥n de Hikari
  
  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true